FirstWebApplication/Controllers/CinemaController.cs
using FirstWebApplication.Models;
using MovieApp.Logic.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApplication.Controllers
{
    public class CinemaController : Controller
    {
        // GET: Cinema
        public ActionResult Index()
        {
            List<CinemaModel> cinemas = CinemaManager.GetCinemas().Select(c=> CinemaModel.FromData(c)).ToList();
           
            return View(cinemas);
        }
        [HttpGet] // get nozīmē apskates forma
        public ActionResult Edit(int? id) // šis bloks nepieciešams lietotāja datu attēlošanai . Jautājuma zīme norāda, ka id var būt tukšs
        {
            CinemaModel cinema = null; // jādefinē kinoteātris, kas jālabo vai jāpievieno
            if (id.HasValue) // ja ID ir definēts, tiek veikta rediģēšana
            {
                cinema = CinemaModel.FromData(CinemaManager.GetCinema(id.Value));
                cinema.Movies = MovieManager.GetMovies(id.Value).Select(m => MovieModel.FromData(m)).ToList();
            } else
            {
                cinema = new CinemaModel(); // ja id nav definēts, tad kinoteātri neatlasam, pievienojam tukšu, lai nav problēmas ar Id lauku
            }
            return View(cinema);
        }

        [HttpPost] // post nozīmē datu iesūtīšana
        public ActionResult Edit(CinemaModel cinema)
        {
            if (ModelState.IsValid) // iebūvēta funkcija, kas pārbauda vai dati atbilst definētajiem 
            {
                
                if(cinema.Id != 0) // ja Id ir nav definēts, tad labojam
                {
                    CinemaManager.Update(cinema.ToData());
                }
                else
                {
                    CinemaManager.Create(cinema.ToData());
                }
                    
            }
            return View(cinema);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            CinemaManager.Delete(id);

            return RedirectToAction("Index");
        }

    }
    
}

FirstWebApplication/Views/Cinema/Edit.cshtml
@model FirstWebApplication.Models.CinemaModel
@{
    ViewBag.Title = "Edit";
}
<h2>@(String.IsNullOrEmpty(Model.Name) ? "New cinema" : Model.Name)</h2>
@using (Html.BeginForm("Edit", "Cinema", FormMethod.Post, new { @class = "form-horizontal" }))


{

    <Div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </Div>
    <Div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>

    </Div>
    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">
            @Html.HiddenFor(m => m.Id)
            <input type="submit" value="Saglabāt" class="btn btn-default">

        </div>
    </div>
    

}

    <table class="table table-striped">
        <tr>
        <td>Nosaukums</td>
        <td>Gads</td>
        </tr>

        @foreach (var movie in Model.Movies)
        {
            <tr>
                <td>@movie.Title</td>
                <td> @movie.Year</td>
            </tr>
        }

    </table>

FirstWebApplication/Views/Cinema/Index.cshtml
@model List<FirstWebApplication.Models.CinemaModel>
@{
    ViewBag.Title = "Kinoteātru saraksts";
}

<h2>Kinoteātri</h2>
<div>
    @Html.ActionLink("Pievienot jaunu", "Edit", "Cinema", null, new { @class = "btn btn-primary" })
</div>
<table class=" table table-striped">
    <tr>
        <th>Nosaukums</th>
        <th>Adrese</th>
        
    </tr>
    @foreach (var cinema in Model)
    {
        <tr>
            <td>@Html.ActionLink(cinema.Name, "Edit", "Cinema", new { id = cinema.Id }, null)</td>
            <td>@cinema.Address</td>
            <td>@Html.ActionLink("Dzēst", "Delete", "Cinema", new { id = cinema.Id }, null)</td>
            
        </tr>
    }
</table>