FirstWebApplication/Controllers/MovieController.cs
using FirstWebApplication.Models;
using MovieApp.Logic.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace FirstWebApplication.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            List<MovieModel> movies = new List<MovieModel>();
            movies = MovieManager.GetMovies().Select(m => MovieModel.FromData(m)).ToList();
            return View(movies);
        }
        [HttpGet]
        public ActionResult Edit(int? id) // šis bloks nepieciešams lietotāja datu attēlošanai . Jautājuma zīme norāda, ka id var būt tukšs
        {
            MovieModel movie = null; // jādefinē kinoteātris, kas jālabo vai jāpievieno
            if (id.HasValue) // ja ID ir definēts, tiek veikta rediģēšana
            {
                movie = MovieModel.FromData(MovieManager.GetMovie(id.Value));
                movie.MovieSessions = MovieSessionManager.GetSessions(id.Value).
                    Select(s => MovieSessionModel.FromData(s)).ToList();
            }
            else
            {
                movie = new MovieModel(); // ja id nav definēts, tad kinoteātri neatlasam, pievienojam tukšu, lai nav problēmas ar Id lauku
            }
            return View(movie);
        }


        [HttpPost] // post nozīmē datu iesūtīšana
        public ActionResult Edit(MovieModel model)
        {
            if (ModelState.IsValid) // iebūvēta funkcija, kas pārbauda vai dati atbilst definētajiem 
            {
               
                    if (model.Id != 0) // ja Id ir nav definēts, tad labojam
                    {
                    MovieManager.Update(model.ToData());

                    }
                    else
                    {
                        MovieManager.Create(model.ToData());
                    }
   
            }
            return RedirectToAction("Edit", "Cinema", new { id = model.CinemaId });
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {

           
                MovieManager.Delete(id);
            


            return RedirectToAction("Index");
        }
    }
}

FirstWebApplication/Controllers/UserController.cs
using FirstWebApplication.Models;
using MovieApp.Logic.Database;
using MovieApp.Logic.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace FirstWebApplication.Controllers

{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel user)
        {
            if (ModelState.IsValid) {
                string error = UserManager.Register(new MovieApp.Logic.Database.User()
                {
                    Email = user.Email,
                    Name = user.Name,
                    Password = user.Password
                    });
                if (error == null)
                {
                    return RedirectToAction("Login");
                }
                else
                    ModelState.AddModelError("", error);
            }
            
            return View(user);
        }
        [HttpGet]
        public ActionResult Register(string Email)
        {
            
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            
            if (ModelState.IsValid)
            {
                User user = UserManager.Login(model.Email, model.Password);
                if(user == null)
                {
                    ModelState.AddModelError("", "Nepareizs epasts/parole");
                }
                else
                {
                    Session.Set(new UserSessionModel()
                    {
                        User = UserModel.FromData(user)
                    });
                    return RedirectToAction("Home", "Home");
                }
                
            }
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Home", "Home");
        }
        [HttpGet]
        public ActionResult MyBasket()
        {
            return View(Session.Get().Basket);
        }
    }
}

FirstWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -My IMDB </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Movie List", "Index", "Movie")</li>
                    <li>@Html.ActionLink("Cinema List", "Index", "Cinema")</li>
                    @if (Session.Get() == null)
                    {
                    <li>@Html.ActionLink("Reģistrēties", "Register", "User")</li>
                    <li>@Html.ActionLink("Pieslēgties", "Login", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("My Basket", "MyBasket", "User")</li>
                        <li>@Html.ActionLink("Logout " + Session.Get().User.Name, "Logout", "User")</li>
                    }


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>