FirstWebApplication/Controllers/MovieSessionController.cs
using FirstWebApplication.Models;
using MovieApp.Logic.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApplication.Controllers
{
    public class MovieSessionController : Controller
    {
        // GET: MovieSession
        public ActionResult Index(int movieId)
        {
            List<MovieSessionModel> sessions = new List<MovieSessionModel>();
            sessions = MovieSessionManager.GetSessions(movieId).Select(s => MovieSessionModel.FromData(s)).ToList();
            return View(sessions);
            
        }
        [HttpGet]
        public ActionResult Edit(int? id, int movieId) 
        {
            MovieSessionModel session = null; 
            if (id.HasValue) 
            {
                session = MovieSessionModel.FromData(MovieSessionManager.GetSession(id.Value));
            }
            else
            {
                session = new MovieSessionModel();
                session.MovieId = movieId;
            }
            return View(session);
        }
        [HttpPost] 
        public ActionResult Edit(MovieSessionModel model)
        {
            if (ModelState.IsValid) 
            {
                if (model.Id != 0) 
                {
                    MovieSessionManager.Update(model.ToData());
                }
                else
                {
                    MovieSessionManager.Create(model.ToData());
                }
            }
            return RedirectToAction("Edit", "Session", new { id = model.MovieId });
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            MovieSessionManager.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

FirstWebApplication/Views/MovieSession/Edit.cshtml
@model FirstWebApplication.Models.MovieSessionModel
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "MovieSession", FormMethod.Post, new { @class = "form-horizontal" }))


{

    <Div class="form-group">
        @Html.LabelFor(m => m.Time, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        </div>
    </Div>
    <Div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>

    </Div>
    <Div class="form-group">
        @Html.LabelFor(m => m.MovieId, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.MovieId, new { @class = "form-control" })
        </div>

    </Div>
    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">
            @Html.HiddenFor(m => m.Id)
            <input type="submit" value="Saglabāt" class="btn btn-default">

        </div>
    </div>


}

FirstWebApplication/Views/MovieSession/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>